apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nginxdeploy-4
  labels:
    app: nginx
spec:
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: nginx
        tier: display
    spec:
      containers:
        - image: nginx
          name: front-end
          imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: nginxservice-4
  labels:
    app: nginx
spec:
  type: NodePort
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
      nodePort: 30090
  selector:
    app: nginx
    tier: display
